=== vlados2108/WT-part2/SecondLab/src/main/resources/appliances_db.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.epam.tc.com/appliances"
           xmlns:tns="http://www.epam.tc.com/appliances">

    <xs:element name="appliances">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="oven" type="tns:ovenType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="laptop" type="tns:laptopType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="refrigerator" type="tns:refrigeratorType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="vacuum-cleaner" type="tns:vacuumCleanerType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="tablet-PC" type="tns:tabletPCType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="speakers" type="tns:speakersType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ovenType">
        <xs:sequence>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="power-consumption" type="xs:double"/>
            <xs:element name="weight" type="xs:double"/>
            <xs:element name="capacity" type="xs:double"/>
            <xs:element name="depth" type="xs:double"/>
            <xs:element name="height" type="xs:double"/>
            <xs:element name="width" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="laptopType">
        <xs:sequence>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="battery-capacity" type="xs:double"/>
            <xs:element name="os" type="tns:os"/>
            <xs:element name="memory-rom" type="xs:double"/>
            <xs:element name="cpu" type="tns:cpu"/>
            <xs:element name="display-inches" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="refrigeratorType">
        <xs:sequence>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="power-consumption" type="xs:double"/>
            <xs:element name="weight" type="xs:double"/>
            <xs:element name="freezer-capacity" type="xs:double"/>
            <xs:element name="overall-capacity" type="xs:double"/>
            <xs:element name="height" type="xs:double"/>
            <xs:element name="width" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="vacuumCleanerType">
        <xs:sequence>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="power-consumption" type="xs:double"/>
            <xs:element name="filter-type" type="tns:filter-type"/>
            <xs:element name="bag-type" type="tns:bag-type"/>
            <xs:element name="wand-type" type="tns:wand-type"/>
            <xs:element name="motor-speed-regulation" type="xs:double"/>
            <xs:element name="cleaning-width" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tabletPCType">
        <xs:sequence>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="battery-capacity" type="xs:double"/>
            <xs:element name="display-inches" type="xs:double"/>
            <xs:element name="memory-rom" type="xs:double"/>
            <xs:element name="flash-memory-capacity" type="xs:double"/>
            <xs:element name="color" type="tns:color"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="speakersType">
        <xs:sequence>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="power-consumption" type="xs:double"/>
            <xs:element name="number-of-speakers" type="xs:int"/>
            <xs:element name="cord-length" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="os">
        <xs:restriction base="xs:string">
            <xs:enumeration value="WINDOWS"/>
            <xs:enumeration value="MACOS"/>
            <xs:enumeration value="LINUX"/>
            <xs:enumeration value="ANDROID"/>
            <xs:enumeration value="IOS"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cpu">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AMD_RYZEN_5_5600X"/>
            <xs:enumeration value="AMD_RYZEN_9_5950X"/>
            <xs:enumeration value="AMD_RYZEN_9_5900X"/>
            <xs:enumeration value="INTEL_CORE_I5_11600K"/>
            <xs:enumeration value="INTEL_CORE_I7_11700K"/>
            <xs:enumeration value="INTEL_CORE_I7_8086K"/>
            <xs:enumeration value="INTEL_CORE_I9_10980XE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="filter-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A"/>
            <xs:enumeration value="B"/>
            <xs:enumeration value="C"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="bag-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A1"/>
            <xs:enumeration value="A2"/>
            <xs:enumeration value="B1"/>
            <xs:enumeration value="B2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="wand-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ALL_IN_ONE"/>
            <xs:enumeration value="LONG"/>
            <xs:enumeration value="SHORT"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="color">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BLUE"/>
            <xs:enumeration value="YELLOW"/>
            <xs:enumeration value="RED"/>
            <xs:enumeration value="GREEN"/>
            <xs:enumeration value="GRAY"/>
            <xs:enumeration value="SILVER"/>
            <xs:enumeration value="BLACK"/>
            <xs:enumeration value="WHITE"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== vlados2108/WT-part2/SecondLab/src/main/resources/appliances_db.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<tc:appliances xmlns:tc="http://www.epam.tc.com/appliances"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.epam.tc.com/appliances appliances_db.xsd">

    <oven>
        <price>100.0</price>
        <power-consumption>1000.0</power-consumption>
        <weight>10.0</weight>
        <capacity>32.0</capacity>
        <depth>60.0</depth>
        <height>45.5</height>
        <width>35.0</width>
    </oven>
    <oven>
        <price>200.0</price>
        <power-consumption>1500.0</power-consumption>
        <weight>12.0</weight>
        <capacity>33.0</capacity>
        <depth>60.0</depth>
        <height>45.0</height>
        <width>60.0</width>
    </oven>
    <oven>
        <price>300.0</price>
        <power-consumption>2000.0</power-consumption>
        <weight>11.0</weight>
        <capacity>33.0</capacity>
        <depth>60.0</depth>
        <height>40.0</height>
        <width>70.0</width>
    </oven>

    <laptop>
        <price>750.0</price>
        <battery-capacity>100.0</battery-capacity>
        <os>WINDOWS</os>
        <memory-rom>4000.0</memory-rom>
        <cpu>AMD_RYZEN_9_5900X</cpu>
        <display-inches>15.5</display-inches>
    </laptop>
    <laptop>
        <price>1000.0</price>
        <battery-capacity>2000.0</battery-capacity>
        <os>MACOS</os>
        <memory-rom>16000.0</memory-rom>
        <cpu>INTEL_CORE_I5_11600K</cpu>
        <display-inches>13.6</display-inches>
    </laptop>
    <laptop>
        <price>2000.0</price>
        <battery-capacity>4000.0</battery-capacity>
        <os>LINUX</os>
        <memory-rom>4000.0</memory-rom>
        <cpu>AMD_RYZEN_5_5600X</cpu>
        <display-inches>17.0</display-inches>
    </laptop>

    <refrigerator>
        <price>1000.0</price>
        <power-consumption>100.0</power-consumption>
        <weight>20.0</weight>
        <freezer-capacity>10.0</freezer-capacity>
        <overall-capacity>300.0</overall-capacity>
        <height>200.0</height>
        <width>70.0</width>
    </refrigerator>
    <refrigerator>
        <price>1400.0</price>
        <power-consumption>150.0</power-consumption>
        <weight>25.0</weight>
        <freezer-capacity>20.0</freezer-capacity>
        <overall-capacity>350.0</overall-capacity>
        <height>150.0</height>
        <width>50.0</width>
    </refrigerator>
    <refrigerator>
        <price>1300.0</price>
        <power-consumption>150.0</power-consumption>
        <weight>40.0</weight>
        <freezer-capacity>20.0</freezer-capacity>
        <overall-capacity>400.0</overall-capacity>
        <height>300.0</height>
        <width>150.0</width>
    </refrigerator>

    <vacuum-cleaner>
        <price>1300.0</price>
        <power-consumption>100.0</power-consumption>
        <filter-type>A</filter-type>
        <bag-type>A1</bag-type>
        <wand-type>ALL_IN_ONE</wand-type>
        <motor-speed-regulation>3000.0</motor-speed-regulation>
        <cleaning-width>20.0</cleaning-width>
    </vacuum-cleaner>
    <vacuum-cleaner>
        <price>1000.0</price>
        <power-consumption>150.0</power-consumption>
        <filter-type>B</filter-type>
        <bag-type>B1</bag-type>
        <wand-type>LONG</wand-type>
        <motor-speed-regulation>2500.0</motor-speed-regulation>
        <cleaning-width>30.0</cleaning-width>
    </vacuum-cleaner>

    <tablet-PC>
        <price>1000.0</price>
        <battery-capacity>400.0</battery-capacity>
        <display-inches>10.0</display-inches>
        <memory-rom>8000.0</memory-rom>
        <flash-memory-capacity>2.0</flash-memory-capacity>
        <color>GREEN</color>
    </tablet-PC>
    <tablet-PC>
        <price>2000.0</price>
        <battery-capacity>300.0</battery-capacity>
        <display-inches>13.0</display-inches>
        <memory-rom>9000.0</memory-rom>
        <flash-memory-capacity>4.0</flash-memory-capacity>
        <color>RED</color>
    </tablet-PC>
    <tablet-PC>
        <price>1600.0</price>
        <battery-capacity>400.0</battery-capacity>
        <display-inches>15.0</display-inches>
        <memory-rom>12000.0</memory-rom>
        <flash-memory-capacity>6.0</flash-memory-capacity>
        <color>BLUE</color>
    </tablet-PC>

    <speakers>
        <price>300.0</price>
        <power-consumption>15.0</power-consumption>
        <number-of-speakers>2</number-of-speakers>
        <cord-length>2.0</cord-length>
    </speakers>
    <speakers>
        <price>400.0</price>
        <power-consumption>16.0</power-consumption>
        <number-of-speakers>3</number-of-speakers>
        <cord-length>3.0</cord-length>
    </speakers>
    <speakers>
        <price>350.0</price>
        <power-consumption>17.0</power-consumption>
        <number-of-speakers>4</number-of-speakers>
        <cord-length>4.0</cord-length>
    </speakers>

</tc:appliances>
